server {
    listen 80;
    server_name _;

    location / {
        root /www/data;
    }

    location /api {
        proxy_pass http://web:8080/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /;

        # Increase timeouts to handle long-running Nmap scans
        proxy_read_timeout 600s;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
    }
}
